### PR TITLE
Adding tfsec and tflint and terraform fmt to guardduty code

### PR DESCRIPTION
**Pull request by partha-gsa**
Change Log

---
* Ran terraform fmt against the code
* added tfsec and tflint to CircleCI config file

### CODE REVIEW

**Review by doug-sillex — APPROVED** [review]
Updated Review See Below

**Review by doug-sillex — CHANGES_REQUESTED** [review]
Replicate changes @rjlupinek suggested on the Ref-Arch-Repo

**Review by rjlupinek — APPROVED** [review]
Looks good!  Rock on! :)

**Review by doug-sillex — APPROVED** [review]
Good to go!

**Pull request merged**
