### PR TITLE
Updating code to push guard duty logs to logging bucket

### PR DESCRIPTION
**Pull request by partha-gsa**

### CODE REVIEW

**Comment by partha-gsa** [comment]
Hi Robert,

I made changes to put guardduty logs to existing logging bucket. please review the code

**Review by rjlupinek — CHANGES_REQUESTED** [review]
Looks good, but I would remove any mentions of grace from the variable names.  This module could be used to populate any bucket.  

I would also delete all of the lines you are commenting out for cleanliness sake.

**Comment by partha-gsa** [comment]
Hi Robert.. can you please check now

**Review by rjlupinek — APPROVED** [review]
Looks good!  Let me know when a new release is cut!  ;)

**Pull request merged**
